# Generated by Django 6.0.3 on 2026-03-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
