# Generated by Django 6.0.3 on 2026-03-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos_app', '0003_task_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitcompletion',
            name='completed',
        ),
        migrations.AddField(
            model_name='habitcompletion',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
