# Generated by Django 6.0.3 on 2026-03-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos_app', '0004_remove_habitcompletion_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='lifeos_app.goal'),
        ),
    ]
