# Generated by Django 6.0.3 on 2026-03-20 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos_app', '0005_task_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='lifeos_app.goal'),
        ),
        migrations.AddField(
            model_name='task',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='lifeos_app.habit'),
        ),
    ]
