# Generated by Django 6.0.3 on 2026-03-20 11:48

from django.db import migrations
import json

def convert_refs_to_json(apps, schema_editor):
    Reflection = apps.get_model('lifeos_app', 'Reflection')
    for ref in Reflection.objects.all():
        try:
            # If it's already structured, skip
            json.loads(ref.content)
        except json.JSONDecodeError:
            data = {
                "wins": ref.content,
                "challenges": "",
                "tomorrow": ""
            }
            ref.content = json.dumps(data)
            ref.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lifeos_app', '0006_habit_goal_task_habit'),
    ]

    operations = [
        migrations.RunPython(convert_refs_to_json),
    ]
