# Generated by Django 6.0.3 on 2026-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos_app', '0007_prepare_reflection_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
