# Generated by Django 6.0.3 on 2026-03-20 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos_app', '0008_alter_reflection_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='tracking_mode',
            field=models.CharField(choices=[('manual_slider', 'Manual with Slider'), ('manual_checkbox', 'Manual with Checkbox'), ('task_driven', 'Task Driven')], default='manual_slider', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('trackable', 'Trackable')], default='simple', max_length=10),
        ),
    ]
