# Generated by Django 6.0.3 on 2026-03-21 04:34

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_data(apps, schema_editor):
    Goal = apps.get_model('lifeos_app', 'Goal')
    Habit = apps.get_model('lifeos_app', 'Habit')
    Task = apps.get_model('lifeos_app', 'Task')

    # All existing goals → default to task_based
    Goal.objects.all().update(
        goal_type='task_based'
    )

    # Migrate habit tracking modes:
    # manual_slider → slider
    # manual_checkbox → checkbox
    # task_driven → slider (safe fallback)
    for habit in Habit.objects.all():
        if hasattr(habit, 'tracking_mode'):
            if habit.tracking_mode == 'manual_checkbox':
                habit.habit_type = 'checkbox'
            else:
                # slider + task_driven → slider
                habit.habit_type = 'slider'
            habit.save()

    # Remove habit FK from all tasks
    Task.objects.all().update(habit=None)


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos_app', '0009_habit_tracking_mode_task_progress_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('task_based', 'Task Based'), ('habit_based', 'Habit Based')], default='task_based', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_days',
            field=models.IntegerField(blank=True, help_text='Only for Habit Based goals', null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('slider', 'Slider')], default='checkbox', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_habits', to='lifeos_app.goal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('trackable', 'Trackable')], default='simple', max_length=20),
        ),
        migrations.RunPython(migrate_existing_data),
        migrations.RemoveField(
            model_name='habit',
            name='tracking_mode',
        ),
        migrations.RemoveField(
            model_name='task',
            name='habit',
        ),
    ]
